### ISSUE TITLE
'bool' object is not subscriptable when running bwm for the first time

### ISSUE THREAD

**Issue by matko031** [firecat53/bitwarden-menu#25]
When running `bwm` for the first time, after providing vault, login and 2FA type, I get the following error:

```Python
Traceback (most recent call last):                                                                      
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/__main__.py", line 174, in main        
    manager = client()                                                                                  
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/__main__.py", line 79, in client       
    mgr.connect()                                                                                       
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 522, in connect                           
    conn = Client(self._address, authkey=self._authkey)                                                 
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 507, in Client                          
    c = SocketClient(address)                                                                           
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient                    
    s.connect(address)                                                                                  
ConnectionRefusedError: [Errno 111] Connection refused                                                  
                                                                                                        
During handling of the above exception, another exception occurred:                                     
                                                                                                        
Traceback (most recent call last):                                                                      
  File "/home/connexounds/.local/bin/bwm", line 8, in <module>                                          
    sys.exit(main())                                                                                    
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/__main__.py", line 181, in main        
    run(**args)                                                                                         
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/__main__.py", line 129, in run         
    dmenu = DmenuRunner(server, **kwargs)                                                               
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/bwm.py", line 382, in __init__         
    self.vaults = get_vault(**kwargs)                                                                   
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/bwm.py", line 114, in get_vault        
    vaults[0] = sel                                                                                     
IndexError: list assignment index out of range
```

When I run `bwm` again after that, the error is gone, but then I get this error which I cannot solve:
```Python
Traceback (most recent call last):
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/__main__.py", line 174, in main
    manager = client()
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/__main__.py", line 79, in client
    mgr.connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 522, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/connexounds/.local/bin/bwm", line 8, in <module>
    sys.exit(main())
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/__main__.py", line 181, in main
    run(**args)
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/__main__.py", line 129, in run
    dmenu = DmenuRunner(server, **kwargs)
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/bwm.py", line 382, in __init__
    self.vaults = get_vault(**kwargs)
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/bwm.py", line 127, in get_vault
    return set_vault(vaults)
  File "/home/connexounds/.local/lib/python3.9/site-packages/bwm/bwm.py", line 146, in set_vault
    if status['status'] == 'unauthenticated':
TypeError: 'bool' object is not subscriptable
```

I installed bitwarden-menu through pip and am running Debian 11. Here is my config file:
```Python
[dmenu]
dmenu_command = dmenu

[dmenu_passphrase]
obscure = True
obscure_color = #222222

[vault]
server_1 = https://vault.bitwarden.com
email_1 = name@email.com
twofactor_1 = 
session_timeout_min = 360
autotype_default = {USERNAME}{TAB}{PASSWORD}{ENTER}

```

**Comment by firecat53** [comment]
Thanks for your interest! What desktop environment are you using? I tried it
using dmenu on XFCE in a Debian 11 vagrant box and it worked fine (other than
one other error that is fixed but isn't released to pip yet). I used the exact
config file that you posted.

Are you logging in to an existing vault or using a new one? Vaultwarden or the
official bitwarden.com? I have both vaultwarden and and a bitwarden.com account
and bwm works fine with both.

**Comment by matko031** [comment]
I'm using i3 and am logging in to an existing bitwarden.com vault.

**Comment by firecat53** [comment]
Ok, I found and fixed a small error.

1. Check the log at ~/.cache/bwm.log. Delete the log if there's nothing interesting.
2. `pip uninstall bitwarden-menu`.
3. Download the source, checkout the `develop` branch and then `pip install --user .`

Try again.

Let me know if that works. Thanks!

**Comment by matko031** [comment]
The issue is still there, but ~/.cache/bwm.log did shine some light as to what might cause it. It complains about permissions when trying to create data.json:
`ERROR:root:CompletedProcess(args=['bw', '--session', b'', 'status'], returncode=1, stdout=b'', stderr=b'Could not find data file, "/home/connexounds/.local/share/bwm/vault.bitwarden.com/data.json"; creating it instead.\nCould not find data file, "/home/connexounds/.local/share/bwm/vault.bitwarden.com/data.json"; creating it instead.\nnode:fs:585\n  handleErrorFromBinding(ctx);\n  ^\n\nError: EACCES: permission denied, open \'/home/connexounds/.local/share/bwm/vault.bitwarden.com/data.json\'\n    at Object.openSync (node:fs:585:3)\n    at Object.openSync (pkg/prelude/bootstrap.js:796:32)\n    at Object.writeFileSync (node:fs:2170:35)\n    at LowdbStorageService.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:36061:49)\n    at Generator.next (<anonymous>)\n    at /snapshot/clients/apps/cli/build/bw.js:36019:71\n    at new Promise (<anonymous>)\n    at /snapshot/clients/apps/cli/build/bw.js:36015:12\n    at LowdbStorageService.init (/snapshot/clients/apps/cli/build/bw.js:36046:16)\n    at LowdbStorageService.value (/snapshot/clients/apps/cli/build/bw.js:2221:22) {\n  errno: -13,\n  syscall: \'open\',\n  code: \'EACCES\',\n  path: \'/home/connexounds/.local/share/bwm/vault.bitwarden.com/data.json\'\n}\n')`

I created the file manually, it then throws the same error about failing to create data.json.lock dir:
`ERROR:root:CompletedProcess(args=['bw', '--session', b'', 'status'], returncode=1, stdout=b'', stderr=b"node:internal/process/promises:279\n            triggerUncaughtException(err, true /* fromPromise */);\n            ^\n\n[Error: EACCES: permission denied, mkdir '/home/connexounds/.local/share/bwm/vault.bitwarden.com/data.json.lock'] {\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'mkdir',\n  path: '/home/connexounds/.local/share/bwm/vault.bitwarden.com/data.json.lock'\n}\n")`

I again creating the directory manually (just to see what would happen) and got a permission error when trying to remove the lock dir:
`ERROR:root:CompletedProcess(args=['bw', '--session', b'', 'status'], returncode=1, stdout=b'', stderr=b"node:internal/process/promises:279\n            triggerUncaughtException(err, true /* fromPromise */);\n            ^\n\n[Error: EACCES: permission denied, rmdir '/home/connexounds/.local/share/bwm/vault.bitwarden.com/data.json.lock'] {\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'rmdir',\n  path: '/home/connexounds/.local/share/bwm/vault.bitwarden.com/data.json.lock'\n}\n")`

The weird thing is that there is an error trying to create those files/dirs even though I gave `~/.local/share/bwm/vault.bitwarden.com` dir 777 permissions. Any idea what might be causing it?

**Comment by firecat53** [comment]
Hmmm...if you were on a Redhat/Suse system I'd suspect SELinux. Is that or apparmor functioning? Did you download `bw` directly from the bitwarden site? Is it up-to-date?

You might test with just the `bw` command line tool to access your vault and see if that functions correctly or not.

**Comment by firecat53** [comment]
Did you ever get this figured out?

**Comment by firecat53** [comment]
Hopefully you got this sorted. Closing as it's stale and I can't reproduce. Let me know if you have more questions!
